{
  lib,
  pkgs,
  config,
  self,
  ...
}:
let
  builderKeyPath = self + "/vars/shared/remote-builder-ssh-key/id_ed25519.pub/value";
in
{

  imports = [
    ../../modules/nixos
  ];

  adeci = {
    base.enable = true;
    dev.enable = true;
    shell.enable = true;
    auto-timezone.enable = false;
    # buildbot-worker = {
    #   enable = true;
    #   workers = 128; # must match cores in buildbot-workers generator's workers.json
    # };
    harmonia.enable = true;
  };

  networking = {
    networkmanager.enable = true;
    hostName = "leviathan";
  };

  time.timeZone = "America/New_York";

  # Transparent Huge Pages configuration for ZGC
  boot.kernelParams = [ "transparent_hugepage=madvise" ];
  systemd.tmpfiles.rules = [
    "w /sys/kernel/mm/transparent_hugepage/shmem_enabled - - - - advise"
    "w /sys/kernel/mm/transparent_hugepage/defrag - - - - defer"
    "w /sys/kernel/mm/transparent_hugepage/khugepaged/defrag - - - - 1"
  ];

  # Nix build server configuration for 256 logical core EPYC system
  nix.settings = {
    max-jobs = 8;
    cores = 32;
    # 32 cores × 8 jobs = 256 cores utilized
    # Some headroom left since not all jobs saturate all cores

    trusted-users = [
      "root"
      "@wheel"
      config.adeci.primaryUser
      "brittonr"
      "dima"
      "fmzakari"
    ];
  };

  # Allow remote builder SSH connections from workstations
  # Key is generated by `clan vars generate` when a machine enables adeci.remote-builder
  users.users.root.openssh.authorizedKeys.keys = lib.optional (builtins.pathExists builderKeyPath) (
    builtins.readFile builderKeyPath
  );

  # A fuse filesystem that dynamically populates contents of /bin
  # and /usr/bin/ so that it contains all executables from the PATH
  # of the requesting process.
  services.envfs.enable = true;

  programs = {

    # I got tired of facing NixOS issues
    # Let's be more pragmatic and try to run binaries sometimes
    # at the cost of sweeping bugs under the rug.
    nix-ld = {
      enable = true;
      libraries = with pkgs; [
        stdenv.cc.cc.lib
        zlib # numpy
      ];
    };

  };

}
